/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.elderxavier.view;

import br.com.elderxavier.controller.DaoPatrimonio;
import br.com.elderxavier.helpers.Helper;
import br.com.elderxavier.model.ControlePatrimonio;
import br.com.elderxavier.resource.topPanel;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author elder
 */
public final class Editar extends javax.swing.JFrame {

    public static String foto;
    public String noFoto = getClass().getResource("/br/com/elderxavier/images/no-image.png").toString().replace("file:", "");
    public static List<ControlePatrimonio> listaPatrimonio;

    public static int registro;
    public static int totalRegistro;

    public Editar() {
        JPanel panel = new topPanel();
        setContentPane(panel);
        initComponents();
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtLocalizacao = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtComposicao = new javax.swing.JTextField();
        sbEstado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlFoto = new javax.swing.JLabel();
        btImage = new javax.swing.JButton();
        txtData = new javax.swing.JFormattedTextField();
        txtCompra = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jbEditar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jbDuplicar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbGofirst = new javax.swing.JButton();
        jbGoback = new javax.swing.JButton();
        jbGonext = new javax.swing.JButton();
        jbGolast = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtRegistro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jlTotalReg = new javax.swing.JLabel();
        jbLimparPesquisa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Patrimonio");
        setBackground(new java.awt.Color(204, 204, 204));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("");
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setAutoscrolls(true);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("ID:");

        jLabel3.setText("CÓDIGO:");
        jLabel3.setToolTipText("");

        jLabel4.setText("DESCRIÇÃO:");

        jLabel5.setText("COMPOSIÇÃO:");

        jLabel6.setText("LOCALIZAÇÃO");

        jLabel7.setText("VALOR DA COMPRA:");

        jLabel8.setText("DATA DA COMPRA:");

        jLabel9.setText("ESTADO DE USO:");

        jLabel10.setText("NOME:");

        sbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOVO", "USADO", "RESTAURADO", "SEGREGADO" }));
        sbEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setText("FOTO:");

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/no-image.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/image-add-icon.png"))); // NOI18N
        btImage.setText("Imagem");
        btImage.setToolTipText("");
        btImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImageActionPerformed(evt);
            }
        });

        txtCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCompraKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(151, 151, 151))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtComposicao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLocalizacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(129, 129, 129)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImage))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btImage))
                .addGap(44, 44, 44))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCodigo, txtComposicao, txtCompra, txtData, txtDescricao, txtId, txtLocalizacao, txtNome});

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/tontos.png"))); // NOI18N

        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/edit-file.png"))); // NOI18N
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/search.png"))); // NOI18N
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbDuplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/duplicate.png"))); // NOI18N
        jbDuplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDuplicarActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/Save-as-icon.png"))); // NOI18N
        jbSalvar.setAlignmentY(0.0F);
        jbSalvar.setAutoscrolls(true);
        jbSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalvar.setBorderPainted(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/new-file.png"))); // NOI18N
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/delete.png"))); // NOI18N
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/logout.png"))); // NOI18N
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(38, 37, 37));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setAutoscrolls(true);

        jbGofirst.setBackground(new java.awt.Color(0, 0, 0));
        jbGofirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/go-first.png"))); // NOI18N
        jbGofirst.setBorder(null);
        jbGofirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGofirstActionPerformed(evt);
            }
        });

        jbGoback.setBackground(new java.awt.Color(0, 0, 0));
        jbGoback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/go-back.png"))); // NOI18N
        jbGoback.setBorder(null);
        jbGoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGobackActionPerformed(evt);
            }
        });

        jbGonext.setBackground(new java.awt.Color(0, 0, 0));
        jbGonext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/go-next.png"))); // NOI18N
        jbGonext.setBorder(null);
        jbGonext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGonextActionPerformed(evt);
            }
        });

        jbGolast.setBackground(new java.awt.Color(0, 0, 0));
        jbGolast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/go-last.png"))); // NOI18N
        jbGolast.setBorder(null);
        jbGolast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGolastActionPerformed(evt);
            }
        });

        jLabel12.setText("Registro");

        jLabel13.setText("de ");

        jlTotalReg.setText("total");

        jbLimparPesquisa.setBackground(new java.awt.Color(51, 51, 51));
        jbLimparPesquisa.setText("Limpar Pesquisa");
        jbLimparPesquisa.setToolTipText("");
        jbLimparPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLimparPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addComponent(jbGofirst, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbGonext, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbGolast, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTotalReg)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbGoback, jbGofirst, jbGolast, jbGonext});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jlTotalReg))
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbGofirst, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGoback, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGonext, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGolast, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimparPesquisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbGoback, jbGofirst, jbGolast, jbGonext});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jbEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDuplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSair)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbDuplicar, jbEditar, jbExcluir, jbNovo, jbPesquisar, jbSair, jbSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jbExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDuplicar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbDuplicar, jbEditar, jbExcluir, jbNovo, jbPesquisar, jbSair, jbSalvar});

        jPanel1.getAccessibleContext().setAccessibleName("topPanel");
        jPanel1.getAccessibleContext().setAccessibleDescription("topPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImageActionPerformed
        Foto jffoto = new Foto();
        try {
            Image icon = ImageIO.read(getClass().getResource("/br/com/elderxavier/images/icon.png"));
            jffoto.setIconImage(icon);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        jffoto.setVisible(true);
        jffoto.jFileChooser1.getSelectedFile();
    }//GEN-LAST:event_btImageActionPerformed

    private void txtCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompraKeyPressed
        String rep = txtCompra.getText();
        int key = evt.getKeyCode();
        char c = (char) evt.getKeyCode();
        rep = c + rep;
        rep = rep.substring(1, rep.length());
        if (rep.length() == 1) {
            rep = "0,0" + rep;
        }

        if (rep.length() >= 2) {
            if (rep.substring(0, 1).equals("0")) {
                rep = rep.substring(1, rep.length());
            }
            rep = rep.replaceAll("[^0-9]", "");
            rep = rep.replaceAll(",", "");
            rep = rep.substring(0, rep.length() - 1) + ',' + rep.substring(rep.length() - 1, rep.length());
        }
        this.txtCompra.setText(rep);
    }//GEN-LAST:event_txtCompraKeyPressed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        this.EnableEntities();
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        this.NewEntity();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        this.SaveEntities();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        this.DeleteEntities();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbDuplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDuplicarActionPerformed
        this.DuplicateEntities();
    }//GEN-LAST:event_jbDuplicarActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        this.SearchEntities();
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbLimparPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparPesquisaActionPerformed
        this.clearSearch();
    }//GEN-LAST:event_jbLimparPesquisaActionPerformed

    private void jbGolastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGolastActionPerformed
        registro = totalRegistro - 1;
        setEntities(listaPatrimonio.get(registro));
        txtRegistro.setText(String.valueOf(registro + 1));
    }//GEN-LAST:event_jbGolastActionPerformed

    private void jbGonextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGonextActionPerformed
        registro = registro < listaPatrimonio.size() - 1 ? registro = registro + 1 : 0;
        setEntities(listaPatrimonio.get(registro));
        txtRegistro.setText(String.valueOf(registro + 1));
    }//GEN-LAST:event_jbGonextActionPerformed

    private void jbGobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGobackActionPerformed
        registro = registro >= 1 ? registro = registro - 1 : listaPatrimonio.size() - 1;
        setEntities(listaPatrimonio.get(registro));
        txtRegistro.setText(String.valueOf(registro + 1));
    }//GEN-LAST:event_jbGobackActionPerformed

    private void jbGofirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGofirstActionPerformed
        this.registro = 0;
        this.setEntities(this.listaPatrimonio.get(this.registro));
        txtRegistro.setText(String.valueOf(this.registro + 1));
    }//GEN-LAST:event_jbGofirstActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Editar editar = new Editar();
                Dimension dDesktop = new Dimension(javax.swing.JFrame.MAXIMIZED_BOTH, javax.swing.JFrame.MAXIMIZED_HORIZ);
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                editar.setLocation((int) (screenSize.getWidth() - editar.getHeight()) / 3, 0);
                editar.setTitle("Controle de Patrimonio");
                try {
                    Image icon = ImageIO.read(getClass().getResource("/br/com/elderxavier/images/icon.png"));
                    editar.setIconImage(icon);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                //editar.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                editar.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbDuplicar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbGoback;
    private javax.swing.JButton jbGofirst;
    private javax.swing.JButton jbGolast;
    private javax.swing.JButton jbGonext;
    public static javax.swing.JButton jbLimparPesquisa;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    public static javax.swing.JLabel jlFoto;
    public static javax.swing.JLabel jlTotalReg;
    public static javax.swing.JComboBox<String> sbEstado;
    public static javax.swing.JTextField txtCodigo;
    public static javax.swing.JTextField txtComposicao;
    public static javax.swing.JFormattedTextField txtCompra;
    public static javax.swing.JFormattedTextField txtData;
    public static javax.swing.JTextField txtDescricao;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtLocalizacao;
    public static javax.swing.JTextField txtNome;
    public static javax.swing.JTextField txtRegistro;
    // End of variables declaration//GEN-END:variables

    public void initForm() {
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            MaskFormatter dateMask = new MaskFormatter("##/##/####");
            dateMask.install(txtData);
            this.DisableEntities();
            txtCompra.setText("0,00");
            DaoPatrimonio dao = new DaoPatrimonio();
            if (dao.getListar().size() > 0) {
                listaPatrimonio = dao.getListar();
                setEntities(listaPatrimonio.get(0));
                registro = 0;
                totalRegistro = listaPatrimonio.size();
                txtRegistro.setText(String.valueOf(registro + 1));
                jlTotalReg.setText(String.valueOf(totalRegistro));
            } else {
                registro = 0;
                totalRegistro = 0;
                jlTotalReg.setText(String.valueOf(totalRegistro));

            }
            jbLimparPesquisa.setVisible(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro: " + ex.toString());
            ex.printStackTrace();
        }

    }

    public void DisableEntities() {
        txtId.setEditable(false);
        txtCodigo.setEditable(false);
        txtCodigo.setEnabled(false);
        txtComposicao.setEditable(false);
        txtComposicao.setEnabled(false);
        txtCompra.setEditable(false);
        txtCompra.setEnabled(false);
        txtData.setEditable(false);
        txtData.setEnabled(false);
        txtDescricao.setEditable(false);
        txtDescricao.setEnabled(false);
        txtLocalizacao.setEditable(false);
        txtLocalizacao.setEnabled(false);
        txtNome.setEditable(false);
        txtNome.setEnabled(false);
        sbEstado.setEnabled(false);
        sbEstado.setEnabled(false);
        btImage.setEnabled(false);
    }

    public void EnableEntities() {
        txtCodigo.setEditable(true);
        txtCodigo.setEnabled(true);
        txtComposicao.setEditable(true);
        txtComposicao.setEnabled(true);
        txtCompra.setEditable(true);
        txtCompra.setEnabled(true);
        txtData.setEditable(true);
        txtData.setEnabled(true);
        txtDescricao.setEditable(true);
        txtDescricao.setEnabled(true);
        txtLocalizacao.setEditable(true);
        txtLocalizacao.setEnabled(true);
        txtNome.setEditable(true);
        txtNome.setEnabled(true);
        sbEstado.setEnabled(true);
        sbEstado.setEnabled(true);
        btImage.setEnabled(true);
    }

    public void NewEntity() {
        jlFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/elderxavier/images/no-image.png")));
        jlFoto.setPreferredSize(new Dimension(350, 350));
        EnableEntities();
        txtId.setText("");
        txtCodigo.setText("");
        txtComposicao.setText("");
        txtCompra.setText("");
        txtData.setText("");
        txtDescricao.setText("");
        txtLocalizacao.setText("");
        txtNome.setText("");

    }

    public void SaveEntities() {
        try {
            ControlePatrimonio patrimonio = this.getEntities();
            DaoPatrimonio dao = new DaoPatrimonio();
            long resp = 0;
            if (patrimonio.getId() > 0) {
                resp = dao.Atualizar(patrimonio, String.valueOf(patrimonio.getId()));
                if (resp > 0) {
                    DisableEntities();
                    listaPatrimonio = dao.getListar();
                }
            } else {
                resp = dao.Inserir(patrimonio);
                if (resp > 0) {
                    txtId.setText(String.valueOf(resp));
                    DisableEntities();
                    listaPatrimonio = dao.getListar();
                    totalRegistro++;
                    jlTotalReg.setText(String.valueOf(totalRegistro));
                    registro = totalRegistro;
                    txtRegistro.setText(String.valueOf(registro));
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            ex.printStackTrace();
        }
    }

    public void DeleteEntities() {
        int op = JOptionPane.showConfirmDialog(null, "Excluir Registro ?", "Cancelar", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            DaoPatrimonio dao = new DaoPatrimonio();
            dao.Excluir(txtId.getText());
            this.DisableEntities();
            listaPatrimonio = dao.getListar();
            totalRegistro--;
            jlTotalReg.setText(String.valueOf(totalRegistro));
            registro = registro - 1;
            txtRegistro.setText(String.valueOf(registro + 1));
            setEntities(listaPatrimonio.get(registro));
            JOptionPane.showMessageDialog(null, "Registro Excluido com sucesso");
        }
    }

    public void DuplicateEntities() {
        setEntities(listaPatrimonio.get(registro));
        this.txtId.setText("");
        EnableEntities();
    }

    public void SearchEntities() {
        Pesquisar jpesquisar = new Pesquisar();
        jpesquisar.setVisible(true);
    }

    /*
    
    
     */
    public ControlePatrimonio getEntities() {
        int id = Helper.IsNumeric(txtId.getText()) ? Integer.parseInt(txtId.getText()) : 0;
        String codigo = !txtCodigo.getText().equals("") ? txtCodigo.getText() : "";
        String composicao = !txtComposicao.getText().equals("") ? txtComposicao.getText() : "";
        String parseValor = txtCompra.getText().replaceAll(",", ".");
        double compra = Helper.IsNumeric(parseValor) ? Double.parseDouble(parseValor) : 0;
        String data = !txtData.getText().equals("") ? txtData.getText() : "";
        String descricao = !txtDescricao.getText().equals("") ? txtDescricao.getText() : "";
        String localizacao = !txtLocalizacao.getText().equals("") ? txtLocalizacao.getText() : "";
        String nome = !txtNome.getText().equals("") ? txtNome.getText() : "";
        String foto = jlFoto.getIcon().toString();
        ControlePatrimonio patrimonio = new ControlePatrimonio();
        patrimonio.setId(id);
        patrimonio.setCodigo(codigo);
        patrimonio.setComposicao(composicao);
        patrimonio.setValor(compra);
        patrimonio.setData(data);
        patrimonio.setDescricao(descricao);
        patrimonio.setLocalizacao(localizacao);
        patrimonio.setNome(nome);
        patrimonio.setFoto(foto);
        patrimonio.setEstado(sbEstado.getSelectedItem().toString());
        return patrimonio;
    }

    public static void setEntities(ControlePatrimonio patrimonio) {
        txtId.setText(String.valueOf(patrimonio.getId()));
        txtCodigo.setText(patrimonio.getCodigo());
        txtComposicao.setText(patrimonio.getComposicao());
        txtData.setText(patrimonio.getData());
        txtDescricao.setText(patrimonio.getDescricao());
        sbEstado.setSelectedItem(patrimonio.getEstado());
        txtLocalizacao.setText(patrimonio.getLocalizacao());
        txtNome.setText(patrimonio.getNome());
        txtCompra.setText(Helper.getDecimalString(patrimonio.getValor()));
        try {
            String pfoto;
            if (patrimonio.getFoto().equals("") || patrimonio.getFoto().equals("null") || patrimonio.getFoto().isEmpty()) {
                foto = "/br/com/elderxavier/images/no-image.png";
            } else {
                File f = new File(patrimonio.getFoto());
                foto = f.exists() && !f.isDirectory() ? patrimonio.getFoto() : foto;
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        jlFoto.setIcon(new javax.swing.ImageIcon(foto));
        jlFoto.setPreferredSize(new Dimension(350, 350));
        jlFoto.setMaximumSize(new Dimension(350, 350));
    }

    public void clearSearch() {        
        DaoPatrimonio dao = new DaoPatrimonio();
        listaPatrimonio = dao.getListar();        
        totalRegistro = listaPatrimonio.size();
        jlTotalReg.setText(String.valueOf(totalRegistro));
        registro = 0;
        setEntities(listaPatrimonio.get(registro));
        txtRegistro.setText(String.valueOf(registro + 1));
        jbLimparPesquisa.setVisible(false);
    }

}
