/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.elderxavier.view;

import br.com.elderxavier.controller.DaoPatrimonio;
import br.com.elderxavier.model.ControlePatrimonio;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author elder
 */
public class Pesquisar extends javax.swing.JFrame {

    public List<ControlePatrimonio> pesquisaPatrimonio;

    private String[] serchItens = new String[8];

    public Pesquisar() {
        initComponents();
        this.initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        sbCodigo = new javax.swing.JCheckBox();
        sbNome = new javax.swing.JCheckBox();
        sbDescricao = new javax.swing.JCheckBox();
        sbComposicao = new javax.swing.JCheckBox();
        sbLocalizacao = new javax.swing.JCheckBox();
        sbValor = new javax.swing.JCheckBox();
        sbEstado = new javax.swing.JCheckBox();
        sbTodos = new javax.swing.JCheckBox();
        sbData = new javax.swing.JCheckBox();
        jlInicio = new javax.swing.JLabel();
        txtDataInicio = new javax.swing.JFormattedTextField();
        jlFim = new javax.swing.JLabel();
        txtDataFim = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jbOk = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        jCheckBox3.setText("jCheckBox3");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Pesquisar");
        setAlwaysOnTop(true);

        jLabel1.setText("Pesquisar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar em:"));

        sbCodigo.setText("CÓDIGO");

        sbNome.setText("NOME");

        sbDescricao.setText("DESCRIÇÃO");

        sbComposicao.setText("COMPOSIÇÃO");

        sbLocalizacao.setText("LOCALIZAÇÃO");

        sbValor.setText("VALOR DA COMPRA");

        sbEstado.setText("ESTADO DE USO");

        sbTodos.setText("SELECIONAR TODOS");
        sbTodos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sbTodosItemStateChanged(evt);
            }
        });

        sbData.setText("DATA");
        sbData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sbDataItemStateChanged(evt);
            }
        });

        jlInicio.setText("INICIO:");

        try {
            txtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jlFim.setText("FIM:");

        try {
            txtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sbCodigo)
                            .addComponent(sbNome)
                            .addComponent(sbDescricao)
                            .addComponent(sbComposicao)
                            .addComponent(sbData))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sbLocalizacao)
                            .addComponent(sbValor)
                            .addComponent(sbEstado)
                            .addComponent(sbTodos)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jlInicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jlFim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDataFim, txtDataInicio});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sbLocalizacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sbValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sbEstado)
                        .addGap(18, 18, 18)
                        .addComponent(sbTodos))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sbCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sbNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sbDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sbComposicao)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbData)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlInicio)
                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFim)
                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtDataFim, txtDataInicio});

        jbOk.setText("OK");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jbCancelar)
                .addGap(31, 31, 31)
                .addComponent(jbOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCancelar, jbOk});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCancelar, jbOk});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.setVisible(false);
        DaoPatrimonio dao = new DaoPatrimonio();
        Editar.listaPatrimonio = dao.getListar();
        Editar.jbLimparPesquisa.setVisible(false);
        Editar.setEntities(Editar.listaPatrimonio.get(0));
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void sbDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sbDataItemStateChanged
        if (sbData.isSelected()) {
            this.showData();
        } else {
            this.hiddenData();
        }
    }//GEN-LAST:event_sbDataItemStateChanged

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        this.SearchPatrimonio();
    }//GEN-LAST:event_jbOkActionPerformed

    private void sbTodosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sbTodosItemStateChanged
        if (sbTodos.isSelected()) {
            sbCodigo.setSelected(true);
            sbComposicao.setSelected(true);
            sbData.setSelected(true);
            sbDescricao.setSelected(true);
            sbEstado.setSelected(true);
            sbLocalizacao.setSelected(true);
            sbNome.setSelected(true);
            sbValor.setSelected(true);
        } else {
            sbCodigo.setSelected(false);
            sbComposicao.setSelected(false);
            sbData.setSelected(false);
            sbDescricao.setSelected(false);
            sbEstado.setSelected(false);
            sbLocalizacao.setSelected(false);
            sbNome.setSelected(false);
            sbValor.setSelected(false);
        }

    }//GEN-LAST:event_sbTodosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pesquisar jfpesquisar = new Pesquisar();
                try {
                    Dimension dDesktop = new Dimension(javax.swing.JFrame.MAXIMIZED_BOTH, javax.swing.JFrame.MAXIMIZED_HORIZ);
                    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                    jfpesquisar.setLocation((int) (screenSize.getWidth() - jfpesquisar.getHeight()) / 3, 100);

                    Image icon = ImageIO.read(getClass().getResource("/br/com/elderxavier/images/icon.png"));
                    jfpesquisar.setIconImage(icon);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                jfpesquisar.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbOk;
    private javax.swing.JLabel jlFim;
    private javax.swing.JLabel jlInicio;
    private javax.swing.JCheckBox sbCodigo;
    private javax.swing.JCheckBox sbComposicao;
    private javax.swing.JCheckBox sbData;
    private javax.swing.JCheckBox sbDescricao;
    private javax.swing.JCheckBox sbEstado;
    private javax.swing.JCheckBox sbLocalizacao;
    private javax.swing.JCheckBox sbNome;
    private javax.swing.JCheckBox sbTodos;
    private javax.swing.JCheckBox sbValor;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables

    protected void initForm() {
        this.hiddenData();
        for (int x = 0; x < serchItens.length; x++) {
            serchItens[x] = "";
        }
    }

    protected void showData() {
        this.jlInicio.setVisible(true);
        this.jlFim.setVisible(true);
        this.txtDataInicio.setVisible(true);
        this.txtDataFim.setVisible(true);
    }

    protected void hiddenData() {
        this.jlInicio.setVisible(false);
        this.jlFim.setVisible(false);
        this.txtDataInicio.setVisible(false);
        this.txtDataFim.setVisible(false);
    }

    protected void SearchPatrimonio() {
        try {
            this.getSelecteds();
            String toSearch = "";
            String searchData = "";
            String comp = "";
            String dataIni = "'1970-01-01 00:00:00'";
            String dataFim = "CURRENT_TIMESTAMP";

            DateFormat dfOld = new SimpleDateFormat("dd/MM/yyyy");
            DateFormat dfNew = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            if (sbData.isSelected()) {
                comp = this.txtDataInicio.getText().replaceAll("[/| ]", "");
                if (comp.length() > 0) {
                    dataIni = this.txtDataInicio.getText();
                    dataIni = "'" + dfNew.format(dfOld.parse(dataIni)) + "'";
                }
                comp = this.txtDataFim.getText().replaceAll("[/| ]", "");
                if (comp.length() > 0) {
                    dataFim = this.txtDataFim.getText();
                    dataFim = "'" + dfNew.format(dfOld.parse(dataFim)) + "'";
                }
            }
            this.serchItens[7] = "data BETWEEN " + dataIni + " AND CURRENT_TIMESTAMP";
            boolean flag = true;
            String aux = "";
            int limit = serchItens.length - 2;
            for (int x = 0; x <= limit; x++) {
                if (x == 0 ) {
                    aux = "";
                } else {
                    aux = " OR ";
                }
                toSearch += !serchItens[x].equals("") ? aux + serchItens[x] : "";
            }
            if (toSearch.equals("")) {
                toSearch = this.serchItens[7];
            } else {
                toSearch = serchItens[7] + " AND (" + toSearch + ")";
            }
            //DaoPatrimonio dao = new DaoPatrimonio();
            if (DaoPatrimonio.getPesquisar(toSearch).size() > 0) {
                Editar.listaPatrimonio = DaoPatrimonio.getPesquisar(toSearch);
                Editar.jbLimparPesquisa.setVisible(true);
                Editar.setEntities(Editar.listaPatrimonio.get(0));
                Editar.registro = 0;
                Editar.totalRegistro = Editar.listaPatrimonio.size();
                Editar.txtRegistro.setText(String.valueOf(Editar.registro + 1));
                Editar.jlTotalReg.setText(String.valueOf(Editar.totalRegistro));
                Editar.jbLimparPesquisa.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, "Nenhum resultado encontrado");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
            ex.printStackTrace();
        }
    }

    private void getSelecteds() {
        if (sbCodigo.isSelected()) {
            this.serchItens[0] = "codigo like '%" + this.txtPesquisar.getText() + "%'";
        } else {
            this.serchItens[0] = "";
        }
        if (sbNome.isSelected()) {
            this.serchItens[1] = "nome like '%" + this.txtPesquisar.getText() + "%'";
        } else {
            this.serchItens[1] = "";
        }
        if (sbDescricao.isSelected()) {
            this.serchItens[2] = "descricao like '%" + this.txtPesquisar.getText() + "%'";
        } else {
            this.serchItens[2] = "";
        }
        if (sbComposicao.isSelected()) {
            this.serchItens[3] = "composicao like '%" + this.txtPesquisar.getText() + "%'";
        } else {
            this.serchItens[3] = "";
        }
        if (sbLocalizacao.isSelected()) {
            this.serchItens[4] = "localizacao like '%" + this.txtPesquisar.getText() + "%'";
        } else {
            this.serchItens[4] = "";
        }
        if (sbValor.isSelected()) {
            this.serchItens[5] = "valor like '%" + this.txtPesquisar.getText() + "%'";
        } else {
            this.serchItens[5] = "";
        }
        if (sbEstado.isSelected()) {
            this.serchItens[6] = "estado like '%" + this.txtPesquisar.getText() + "%'";
        } else {
            this.serchItens[6] = "";
        }
    }

}
